spring:
   rabbitmq:
      addresses: 10.0.209.73:5672
      username: rabbitadmin
      password: 123456
      virtual-host: /
      publisher-confirms: true # 开启生产者端确认机制（默认flase）：确认是否到达交换器；代码中实现 ConfirmCallBack
      publisher-returns: true # 开启生产者端确认机制（默认flase）：确认是否到达队列；代码中实现 ReturnCallback
      template:
         mandatory: true
         
   datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 1020
      driverClassName: com.mysql.jdbc.Driver
      hikari: 
         readOnly: false
         connectionTimeout: 60000
         idleTimeout: 60000
         validationTimeout: 3000
         maxLifetime: 60000
         loginTimeout: 5
         maximumPoolSize: 60
         minimumIdle: 10
         connection-test-query: select 1 
         
server:
   port: 8001
   servlet:
      context-path: /
mybatis:
   mapper-locations: classpath:mapper/*.xml
   #type-aliases-package: com.sxw.springbootproducer

   
logging:
   level:
      tk:
         mybatis: trace
