server:
  port: 9901
spring:
  batch:
    job:
      enabled: false  # job不随着项目的启动而执行
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 1020
  jpa:
    generate-ddl: false
    show-sql: true
    auto-ddl: update
    open-in-view: false
init-db: false

endpoints:
  health:
    sensitive: true
  shutdown:
    enabled: true
    sensitive: true

management:
  security:
    enabled: false
  context-path: '/admin'
  port: 9902

datasource-reader:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springbatch_reader?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 1020
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: false
    sql-script-encoding: UTF-8

datasource-writer:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springbatch_writer?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 1020
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: false
    sql-script-encoding: UTF-8


hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: create-drop
  ejb:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  show_sql: true
  format_sql: true

logging:
  level:
    org:
      springframework: INFO #WARN
      hibernate: INFO #WARN
      