server:
   port: 8080

spring:
   session:
      store-type: redis   
   cache:
      type: redis
   redis:
      database: 0  
      host: 10.0.209.73  #127.0.0.1
      port: 9380
      password: redis123
      # 连接超时时间（毫秒）
      timeout: 2000 
      # spring-data-redis2.0以前都是基于jedis连接，2.0之后的版本都基于lettuce（多前程下更安全）
      jedis: # lettuce:
         pool:
            # 连接池最大连接数（使用负值表示没有限制）
            max-active: 8  
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1  
            # 连接池中的最大空闲连接
            max-idle: 8  
            # 连接池中的最小空闲连接
            min-idle: 0
            
redis-cache:
   default-expire-time: -1 #默认30分钟
   names-and-expires: 
      mapListCache: 1800
      
# 使用logback打印日志   
logging:
   level:
      org.oauth2.test: debug
   